typography_spectrum: 0.8892758425790817
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.6053181367460638
  lightness: 0.09505430026911199
  saturation: 0.8638956581708044
  rhythmicContrast: 0.9917239707428962
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4430913950782269
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3573dfe7-75b1-4a27-be70-bab57e898e05.png
name: Cabaret Rhizome
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Follow the Right Rabbit
description: Follow the right rabbit!
purpose: []
