name: Cabaret Rhizome
favicon: null
layout_spectrum: 0.77256
typography_spectrum: 0.4639176703058183
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#85b2db'
    - '#030303'
    - '#ffffff'
    - '#4a4a4a'
    - '#c27828'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
