typography_spectrum: 0.89463483938016
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.26700094575062394
  lightness: 0.1745963180437684
  saturation: 0.9503555232658982
  rhythmicContrast: 0.8206771751865745
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3748720483854413
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3573dfe7-75b1-4a27-be70-bab57e898e05.png
name: Cabaret Rhizome
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ''
description: Follow the right rabbit!
purpose: []
