name: Cabaret Rhizome
favicon: null
layout_spectrum: 1
typography_spectrum: 0.16078
title: Cabaret Rhizome
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#85b2db'
    - '#030303'
    - '#ffffff'
    - '#4a4a4a'
    - '#c27828'
  brandStrength: 1
  lightness: 0.625
  saturation: 1
  rhythmicContrast: 0
purpose: []
