typography_spectrum: 0.16078
color:
  brandColors:
    - '#85b2db'
    - '#030303'
    - '#ffffff'
    - '#4a4a4a'
    - '#c27828'
  brandStrength: 1
  lightness: 0.625
  saturation: 1
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.48906
analytics:
  google: null
  facebook: null
  twitter: null
name: Cabaret Rhizome
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Cabaret Rhizome
description: Follow the right rabbit!
purpose: []
